---
- name: KABOOM!
  hosts: all
 
  tasks:
  
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: "{{ ip }}:80"
      username: admin
      password: "{{ pass }}"
      reauthorize: yes
      
  - name: remove container
    docker_container:
      name: tomcat3
      force_kill: yes
      state: absent

  - name: Remove image
    docker_image:
      force_absent: yes
      state: absent
      name: "{{ ip }}:80/{{ service }}/{{ serviceimage }}:{{ tag }}"
      tag: latest

  - name: pull image
    docker_image:
      name: "{{ ip }}:80/{{ service }}/{{ serviceimage }}:{{ tag }}"
      source: pull

  - name: Run `docker-compose up` again
    docker_compose:
      project_src: /home/kalyan/test
      build: no
