---
- name: KABOOM!
  hosts: all
 
  tasks:
  
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: 192.168.218.130:80
      username: admin
      password: Harbor12345
      reauthorize: yes
      
  - name: remove container
    docker_container:
      name: tomcat3
      force_kill: yes
      state: absent

  - name: Remove image
    docker_image:
      force_absent: yes
      state: absent
      name: 192.168.218.130:80/portalapp/portalappimage
      tag: latest

  - name: pull image
    docker_image:
      name: 192.168.218.130:80/portalapp/portalappimage:latest
      source: pull

  - name: Run `docker-compose up` again
    docker_compose:
      project_src: /home/kalyan/test
      build: no
